// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Employee Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Employee Login', async function() {
    // Test name: Employee Login
    // Step # | name | target | value
    // 1 | open | /api/login | 
    await driver.get("https://staff-grid.vercel.app/api/login")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect(1552, 832)
    // 3 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 4 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 5 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 6 | type | id=id | 2024030001
    await driver.findElement(By.id("id")).sendKeys("2024030001")
    // 7 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 8 | type | id=password | R123456
    await driver.findElement(By.id("password")).sendKeys("R123456")
    // 9 | click | css=.login-btn | 
    await driver.findElement(By.css(".login-btn")).click()
    // 10 | click | css=.hamburger | 
    await driver.findElement(By.css(".hamburger")).click()
    // 11 | click | linkText=Apply Leave | 
    await driver.findElement(By.linkText("Apply Leave")).click()
    // 12 | click | css=.main1 | 
    await driver.findElement(By.css(".main1")).click()
    // 13 | click | css=.close | 
    await driver.findElement(By.css(".close")).click()
    // 14 | click | name=leaveType | 
    await driver.findElement(By.name("leaveType")).click()
    // 15 | click | name=fromDate | 
    await driver.findElement(By.name("fromDate")).click()
    // 16 | type | name=fromDate | 2024-12-02
    await driver.findElement(By.name("fromDate")).sendKeys("2024-12-02")
    // 17 | click | name=toDate | 
    await driver.findElement(By.name("toDate")).click()
    // 18 | type | name=toDate | 2024-12-07
    await driver.findElement(By.name("toDate")).sendKeys("2024-12-07")
    // 19 | click | css=.submit | 
    await driver.findElement(By.css(".submit")).click()
    // 20 | mouseOver | css=.submit | 
    {
      const element = await driver.findElement(By.css(".submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 21 | click | css=tr:nth-child(2) .cancel-button | 
    await driver.findElement(By.css("tr:nth-child(2) .cancel-button")).click()
  })
})
