// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('New ID Profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('New ID Profile', async function() {
    // Test name: New ID Profile
    // Step # | name | target | value
    // 1 | open | /api/login | 
    await driver.get("https://staff-grid.vercel.app/api/login")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect(1552, 832)
    // 3 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 4 | type | id=id | 2024020004
    await driver.findElement(By.id("id")).sendKeys("2024020004")
    // 5 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 6 | type | id=password | vTq@Vc0j
    await driver.findElement(By.id("password")).sendKeys("vTq@Vc0j")
    // 7 | click | css=.login-btn | 
    await driver.findElement(By.css(".login-btn")).click()
    // 8 | click | css=.hamburger | 
    await driver.findElement(By.css(".hamburger")).click()
    // 9 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 10 | click | css=.close | 
    await driver.findElement(By.css(".close")).click()
    // 11 | click | name=firstName | 
    await driver.findElement(By.name("firstName")).click()
    // 12 | type | name=firstName | Jeet2
    await driver.findElement(By.name("firstName")).sendKeys("Jeet2")
    // 13 | type | name=lastName | Patel
    await driver.findElement(By.name("lastName")).sendKeys("Patel")
    // 14 | type | name=fatherName | kri2
    await driver.findElement(By.name("fatherName")).sendKeys("kri2")
    // 15 | type | name=motherName | prl2
    await driver.findElement(By.name("motherName")).sendKeys("prl2")
    // 16 | type | name=birthDate | 0002-07-04
    await driver.findElement(By.name("birthDate")).sendKeys("0002-07-04")
    // 17 | type | name=birthDate | 0020-07-04
    await driver.findElement(By.name("birthDate")).sendKeys("0020-07-04")
    // 18 | type | name=birthDate | 0200-07-04
    await driver.findElement(By.name("birthDate")).sendKeys("0200-07-04")
    // 19 | type | name=birthDate | 2004-07-04
    await driver.findElement(By.name("birthDate")).sendKeys("2004-07-04")
    // 20 | click | name=phoneNumber | 
    await driver.findElement(By.name("phoneNumber")).click()
    // 21 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 22 | click | name=phoneNumber | 
    await driver.findElement(By.name("phoneNumber")).click()
    // 23 | type | name=phoneNumber | 7861926571
    await driver.findElement(By.name("phoneNumber")).sendKeys("7861926571")
    // 24 | click | name=nationality | 
    await driver.findElement(By.name("nationality")).click()
    // 25 | type | name=nationality | Ind
    await driver.findElement(By.name("nationality")).sendKeys("Ind")
    // 26 | click | name=religion | 
    await driver.findElement(By.name("religion")).click()
    // 27 | type | name=religion | Hnd
    await driver.findElement(By.name("religion")).sendKeys("Hnd")
    // 28 | click | name=block | 
    await driver.findElement(By.name("block")).click()
    // 29 | type | name=block | C-211
    await driver.findElement(By.name("block")).sendKeys("C-211")
    // 30 | click | name=street | 
    await driver.findElement(By.name("street")).click()
    // 31 | type | name=street | DAIICT
    await driver.findElement(By.name("street")).sendKeys("DAIICT")
    // 32 | click | name=village | 
    await driver.findElement(By.name("village")).click()
    // 33 | type | name=village | DAIICT
    await driver.findElement(By.name("village")).sendKeys("DAIICT")
    // 34 | click | name=taluka | 
    await driver.findElement(By.name("taluka")).click()
    // 35 | type | name=taluka | DAIICT
    await driver.findElement(By.name("taluka")).sendKeys("DAIICT")
    // 36 | click | name=district | 
    await driver.findElement(By.name("district")).click()
    // 37 | type | name=district | DAIICT
    await driver.findElement(By.name("district")).sendKeys("DAIICT")
    // 38 | click | name=pincode | 
    await driver.findElement(By.name("pincode")).click()
    // 39 | type | name=pincode | 389001
    await driver.findElement(By.name("pincode")).sendKeys("389001")
    // 40 | click | name=state | 
    await driver.findElement(By.name("state")).click()
    // 41 | type | name=state | Gujarat
    await driver.findElement(By.name("state")).sendKeys("Gujarat")
    // 42 | click | name=country | 
    await driver.findElement(By.name("country")).click()
    // 43 | type | name=country | Ind
    await driver.findElement(By.name("country")).sendKeys("Ind")
    // 44 | click | name=bankName | 
    await driver.findElement(By.name("bankName")).click()
    // 45 | type | name=bankName | ICICI
    await driver.findElement(By.name("bankName")).sendKeys("ICICI")
    // 46 | click | name=ifscCode | 
    await driver.findElement(By.name("ifscCode")).click()
    // 47 | type | name=ifscCode | ICIC0256314
    await driver.findElement(By.name("ifscCode")).sendKeys("ICIC0256314")
    // 48 | click | name=accountNo | 
    await driver.findElement(By.name("accountNo")).click()
    // 49 | type | name=accountNo | 123456789
    await driver.findElement(By.name("accountNo")).sendKeys("123456789")
    // 50 | click | name=aadharNumber | 
    await driver.findElement(By.name("aadharNumber")).click()
    // 51 | type | name=aadharNumber | 123456789123
    await driver.findElement(By.name("aadharNumber")).sendKeys("123456789123")
  })
})
