// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Employee view', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Employee view', async function() {
    // Test name: Employee view
    // Step # | name | target | value
    // 1 | open | https://staff-grid.vercel.app/api/login | 
    await driver.get("https://staff-grid.vercel.app/api/login")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect(1552, 832)
    // 3 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 4 | type | id=id | 2024000001
    await driver.findElement(By.id("id")).sendKeys("2024000001")
    // 5 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 6 | type | id=password | R123456
    await driver.findElement(By.id("password")).sendKeys("R123456")
    // 7 | click | css=.login-btn | 
    await driver.findElement(By.css(".login-btn")).click()
    // 8 | click | css=.hamburger | 
    await driver.findElement(By.css(".hamburger")).click()
    // 9 | click | linkText=All Employee View | 
    await driver.findElement(By.linkText("All Employee View")).click()
    // 10 | click | css=.close | 
    await driver.findElement(By.css(".close")).click()
    // 11 | click | css=.cardpeople:nth-child(28) path | 
    await driver.findElement(By.css(".cardpeople:nth-child(28) path")).click()
    // 12 | click | css=.logout | 
    await driver.findElement(By.css(".logout")).click()
  })
})
