// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('leave Approal ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('leave Approal ', async function() {
    // Test name: leave Approal 
    // Step # | name | target | value
    // 1 | open | https://staff-grid.vercel.app/api/login | 
    await driver.get("https://staff-grid.vercel.app/api/login")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect(1552, 832)
    // 3 | click | id=id | 
    await driver.findElement(By.id("id")).click()
    // 4 | type | id=id | 2024000001
    await driver.findElement(By.id("id")).sendKeys("2024000001")
    // 5 | type | id=password | R123456
    await driver.findElement(By.id("password")).sendKeys("R123456")
    // 6 | click | css=.login-btn | 
    await driver.findElement(By.css(".login-btn")).click()
    // 7 | click | css=.hamburger | 
    await driver.findElement(By.css(".hamburger")).click()
    // 8 | click | linkText=Leave Handle | 
    await driver.findElement(By.linkText("Leave Handle")).click()
    // 9 | mouseOver | linkText=Profile | 
    {
      const element = await driver.findElement(By.linkText("Profile"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | mouseOut | linkText=Profile | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 11 | click | css=.close | 
    await driver.findElement(By.css(".close")).click()
    // 12 | click | css=tr:nth-child(1) path | 
    await driver.findElement(By.css("tr:nth-child(1) path")).click()
    // 13 | click | name=leaveStatus | 
    await driver.findElement(By.name("leaveStatus")).click()
    // 14 | select | name=leaveStatus | label=Approved
    {
      const dropdown = await driver.findElement(By.name("leaveStatus"))
      await dropdown.findElement(By.xpath("//option[. = 'Approved']")).click()
    }
    // 15 | click | name=comment | 
    await driver.findElement(By.name("comment")).click()
    // 16 | type | name=comment | get well soon
    await driver.findElement(By.name("comment")).sendKeys("get well soon")
    // 17 | click | css=button:nth-child(3) | 
    await driver.findElement(By.css("button:nth-child(3)")).click()
    // 18 | click | css=.logout | 
    await driver.findElement(By.css(".logout")).click()
  })
})
